/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

export * as checkUserAccess from "./simplespace/checkUserAccess.ts";
export * as createSpace from "./simplespace/createSpace.ts";
export * as defs from "./simplespace/defs.ts";
export * as deleteSpace from "./simplespace/deleteSpace.ts";
export * as getSpace from "./simplespace/getSpace.ts";
export * as listMembers from "./simplespace/listMembers.ts";
export * as putMember from "./simplespace/putMember.ts";
export * as removeMember from "./simplespace/removeMember.ts";
export * as updateSpace from "./simplespace/updateSpace.ts";
